#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gc
Version  : 7_6_0
Release  : 7
URL      : https://github.com/ivmai/bdwgc/archive/gc7_6_0.tar.gz
Source0  : https://github.com/ivmai/bdwgc/archive/gc7_6_0.tar.gz
Summary  : A garbage collector for C and C++
Group    : Development/Tools
License  : BSD-2-Clause
Requires: gc-lib
Requires: gc-data
BuildRequires : cmake
BuildRequires : libatomic_ops-dev
BuildRequires : pkgconfig(atomic_ops)

%description
gc.def should probably be removed completely.
I removed an apparently erroneous line for GC_CreateThread.  Unfortunately
gc.def is referenced in various other places I cannot easily edit.  -HB

%package data
Summary: data components for the gc package.
Group: Data

%description data
data components for the gc package.


%package dev
Summary: dev components for the gc package.
Group: Development
Requires: gc-lib
Requires: gc-data
Provides: gc-devel

%description dev
dev components for the gc package.


%package lib
Summary: lib components for the gc package.
Group: Libraries
Requires: gc-data

%description lib
lib components for the gc package.


%prep
%setup -q -n bdwgc-gc7_6_0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484672569
%autogen --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/gc/AUTHORS
/usr/share/gc/README.DGUX386
/usr/share/gc/README.Mac
/usr/share/gc/README.OS2
/usr/share/gc/README.amiga
/usr/share/gc/README.arm.cross
/usr/share/gc/README.autoconf
/usr/share/gc/README.cmake
/usr/share/gc/README.cords
/usr/share/gc/README.darwin
/usr/share/gc/README.environment
/usr/share/gc/README.ews4800
/usr/share/gc/README.hp
/usr/share/gc/README.linux
/usr/share/gc/README.macros
/usr/share/gc/README.md
/usr/share/gc/README.rs6000
/usr/share/gc/README.sgi
/usr/share/gc/README.solaris2
/usr/share/gc/README.symbian
/usr/share/gc/README.uts
/usr/share/gc/README.win32
/usr/share/gc/README.win64
/usr/share/gc/debugging.html
/usr/share/gc/finalization.html
/usr/share/gc/gc.man
/usr/share/gc/gcdescr.html
/usr/share/gc/gcinterface.html
/usr/share/gc/leak.html
/usr/share/gc/overview.html
/usr/share/gc/porting.html
/usr/share/gc/scale.html
/usr/share/gc/simple_example.html
/usr/share/gc/tree.html

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/gc/cord.h
/usr/include/gc/cord_pos.h
/usr/include/gc/ec.h
/usr/include/gc/gc.h
/usr/include/gc/gc_allocator.h
/usr/include/gc/gc_backptr.h
/usr/include/gc/gc_config_macros.h
/usr/include/gc/gc_disclaim.h
/usr/include/gc/gc_gcj.h
/usr/include/gc/gc_inline.h
/usr/include/gc/gc_mark.h
/usr/include/gc/gc_pthread_redirects.h
/usr/include/gc/gc_tiny_fl.h
/usr/include/gc/gc_typed.h
/usr/include/gc/gc_version.h
/usr/include/gc/javaxfc.h
/usr/include/gc/leak_detector.h
/usr/include/gc/weakpointer.h
/usr/lib64/libcord.so
/usr/lib64/libgc.so
/usr/lib64/pkgconfig/bdw-gc.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcord.so.1
/usr/lib64/libcord.so.1.0.3
/usr/lib64/libgc.so.1
/usr/lib64/libgc.so.1.0.3
