#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gc
Version  : 7.6.4
Release  : 12
URL      : https://github.com/ivmai/bdwgc/releases/download/v7.6.4/gc-7.6.4.tar.gz
Source0  : https://github.com/ivmai/bdwgc/releases/download/v7.6.4/gc-7.6.4.tar.gz
Summary  : A garbage collector for C and C++
Group    : Development/Tools
License  : BSD-2-Clause
Requires: gc-lib
Requires: gc-doc
BuildRequires : cmake
BuildRequires : libatomic_ops-dev
BuildRequires : pkgconfig(atomic_ops)

%description
THIS MATERIAL IS PROVIDED AS IS, WITH ABSOLUTELY NO WARRANTY EXPRESSED
OR IMPLIED.  ANY USE IS AT YOUR OWN RISK.

%package dev
Summary: dev components for the gc package.
Group: Development
Requires: gc-lib
Provides: gc-devel

%description dev
dev components for the gc package.


%package doc
Summary: doc components for the gc package.
Group: Documentation

%description doc
doc components for the gc package.


%package lib
Summary: lib components for the gc package.
Group: Libraries

%description lib
lib components for the gc package.


%prep
%setup -q -n gc-7.6.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1516999606
%autogen --disable-static --enable-cplusplus
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1516999606
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/gc/cord.h
/usr/include/gc/cord_pos.h
/usr/include/gc/ec.h
/usr/include/gc/gc.h
/usr/include/gc/gc_allocator.h
/usr/include/gc/gc_backptr.h
/usr/include/gc/gc_config_macros.h
/usr/include/gc/gc_cpp.h
/usr/include/gc/gc_disclaim.h
/usr/include/gc/gc_gcj.h
/usr/include/gc/gc_inline.h
/usr/include/gc/gc_mark.h
/usr/include/gc/gc_pthread_redirects.h
/usr/include/gc/gc_tiny_fl.h
/usr/include/gc/gc_typed.h
/usr/include/gc/gc_version.h
/usr/include/gc/javaxfc.h
/usr/include/gc/leak_detector.h
/usr/include/gc/weakpointer.h
/usr/lib64/libcord.so
/usr/lib64/libgc.so
/usr/lib64/libgccpp.so
/usr/lib64/pkgconfig/bdw-gc.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/gc/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcord.so.1
/usr/lib64/libcord.so.1.3.0
/usr/lib64/libgc.so.1
/usr/lib64/libgc.so.1.3.2
/usr/lib64/libgccpp.so.1
/usr/lib64/libgccpp.so.1.3.1
