#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gc
Version  : 8.0.4
Release  : 18
URL      : https://github.com/ivmai/bdwgc/releases/download/v8.0.4/gc-8.0.4.tar.gz
Source0  : https://github.com/ivmai/bdwgc/releases/download/v8.0.4/gc-8.0.4.tar.gz
Summary  : A garbage collector for C and C++
Group    : Development/Tools
License  : BSD-2-Clause
Requires: gc-lib = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : libatomic_ops-dev
BuildRequires : pkgconfig(atomic_ops)

%description
THIS MATERIAL IS PROVIDED AS IS, WITH ABSOLUTELY NO WARRANTY EXPRESSED
OR IMPLIED.  ANY USE IS AT YOUR OWN RISK.

%package dev
Summary: dev components for the gc package.
Group: Development
Requires: gc-lib = %{version}-%{release}
Provides: gc-devel = %{version}-%{release}
Requires: gc = %{version}-%{release}

%description dev
dev components for the gc package.


%package doc
Summary: doc components for the gc package.
Group: Documentation

%description doc
doc components for the gc package.


%package lib
Summary: lib components for the gc package.
Group: Libraries

%description lib
lib components for the gc package.


%prep
%setup -q -n gc-8.0.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1561065862
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static --enable-cplusplus
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1561065862
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/gc/cord.h
/usr/include/gc/cord_pos.h
/usr/include/gc/ec.h
/usr/include/gc/gc.h
/usr/include/gc/gc_allocator.h
/usr/include/gc/gc_backptr.h
/usr/include/gc/gc_config_macros.h
/usr/include/gc/gc_cpp.h
/usr/include/gc/gc_gcj.h
/usr/include/gc/gc_inline.h
/usr/include/gc/gc_mark.h
/usr/include/gc/gc_pthread_redirects.h
/usr/include/gc/gc_tiny_fl.h
/usr/include/gc/gc_typed.h
/usr/include/gc/gc_version.h
/usr/include/gc/javaxfc.h
/usr/include/gc/leak_detector.h
/usr/lib64/libcord.so
/usr/lib64/libgc.so
/usr/lib64/libgccpp.so
/usr/lib64/pkgconfig/bdw-gc.pc
/usr/share/man/man3/gc.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/gc/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcord.so.1
/usr/lib64/libcord.so.1.4.0
/usr/lib64/libgc.so.1
/usr/lib64/libgc.so.1.4.3
/usr/lib64/libgccpp.so.1
/usr/lib64/libgccpp.so.1.4.0
